os: linux
dist: xenial
language: cpp
compiler: gcc
sudo: false

script:
  - make
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code  


notifications:
  email:
    recipients:
      - kill-20-20@mail.ru
    on_success: never
on_failure: never 
